# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.1.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.2
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
